
package penghitungdzikir;

public class tahmid extends javax.swing.JFrame {

    public tahmid() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnC = new javax.swing.JButton();
        jumlahtahmid = new javax.swing.JTextField();
        btntahmid1 = new javax.swing.JButton();
        btnbacktahmid = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penghitungdzikir/btnclear.png"))); // NOI18N
        btnC.setBorder(null);
        btnC.setBorderPainted(false);
        btnC.setContentAreaFilled(false);
        btnC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 60, 60));

        jumlahtahmid.setEditable(false);
        jumlahtahmid.setFont(new java.awt.Font("Futura Bk BT", 0, 48)); // NOI18N
        jumlahtahmid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jumlahtahmid.setBorder(null);
        jumlahtahmid.setOpaque(false);
        jumlahtahmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahtahmidActionPerformed(evt);
            }
        });
        getContentPane().add(jumlahtahmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 260, 140));

        btntahmid1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penghitungdzikir/btn1.png"))); // NOI18N
        btntahmid1.setBorder(null);
        btntahmid1.setBorderPainted(false);
        btntahmid1.setContentAreaFilled(false);
        btntahmid1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntahmid1.setFocusPainted(false);
        btntahmid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntahmid1ActionPerformed(evt);
            }
        });
        getContentPane().add(btntahmid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 100, 100));

        btnbacktahmid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penghitungdzikir/btnBack.png"))); // NOI18N
        btnbacktahmid.setBorder(null);
        btnbacktahmid.setBorderPainted(false);
        btnbacktahmid.setContentAreaFilled(false);
        btnbacktahmid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbacktahmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacktahmidActionPerformed(evt);
            }
        });
        getContentPane().add(btnbacktahmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penghitungdzikir/3tahmid.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnbacktahmidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacktahmidActionPerformed
        home jump = new home();        
        jump.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbacktahmidActionPerformed

    private void jumlahtahmidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahtahmidActionPerformed
        
    }//GEN-LAST:event_jumlahtahmidActionPerformed

    private int count;
    private void btntahmid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntahmid1ActionPerformed
        count++;
        jumlahtahmid.setText (Integer.toString(count));
      
    }//GEN-LAST:event_btntahmid1ActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        int reset = 0;
        jumlahtahmid.setText(String.valueOf(reset));
    }//GEN-LAST:event_btnCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tahmid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tahmid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tahmid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tahmid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tahmid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnbacktahmid;
    private javax.swing.JButton btntahmid1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumlahtahmid;
    // End of variables declaration//GEN-END:variables
}
