
package penghitungdzikir;

public class takbir extends javax.swing.JFrame {

    public takbir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnC = new javax.swing.JButton();
        btntakbir1 = new javax.swing.JButton();
        btnbacktakbir = new javax.swing.JButton();
        jumlahtakbir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penghitungdzikir/btnclear.png"))); // NOI18N
        btnC.setBorder(null);
        btnC.setBorderPainted(false);
        btnC.setContentAreaFilled(false);
        btnC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 60, 60));

        btntakbir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penghitungdzikir/btn1.png"))); // NOI18N
        btntakbir1.setBorder(null);
        btntakbir1.setBorderPainted(false);
        btntakbir1.setContentAreaFilled(false);
        btntakbir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntakbir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntakbir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btntakbir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 100, 100));

        btnbacktakbir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penghitungdzikir/btnBack.png"))); // NOI18N
        btnbacktakbir.setBorder(null);
        btnbacktakbir.setBorderPainted(false);
        btnbacktakbir.setContentAreaFilled(false);
        btnbacktakbir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbacktakbir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacktakbirActionPerformed(evt);
            }
        });
        getContentPane().add(btnbacktakbir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 80));

        jumlahtakbir.setFont(new java.awt.Font("Futura Bk BT", 0, 48)); // NOI18N
        jumlahtakbir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jumlahtakbir.setBorder(null);
        jumlahtakbir.setOpaque(false);
        jumlahtakbir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahtakbirActionPerformed(evt);
            }
        });
        getContentPane().add(jumlahtakbir, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 260, 260, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penghitungdzikir/5takbir.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbacktakbirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacktakbirActionPerformed
        home jump = new home();        
        jump.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbacktakbirActionPerformed

    private void jumlahtakbirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahtakbirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahtakbirActionPerformed
    
    private int count;
    private void btntakbir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntakbir1ActionPerformed
        count++;
        jumlahtakbir.setText (Integer.toString(count));
    }//GEN-LAST:event_btntakbir1ActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        int reset = 0;
        jumlahtakbir.setText(String.valueOf(reset));
    }//GEN-LAST:event_btnCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(takbir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(takbir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(takbir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(takbir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new takbir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnbacktakbir;
    private javax.swing.JButton btntakbir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jumlahtakbir;
    // End of variables declaration//GEN-END:variables
}
