
package penghitungdzikir;

public class tasbih extends javax.swing.JFrame {

    public tasbih() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnC = new javax.swing.JButton();
        btntasbih1 = new javax.swing.JButton();
        btnbacktasbih = new javax.swing.JButton();
        jumlahtasbih = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penghitungdzikir/btnclear.png"))); // NOI18N
        btnC.setBorder(null);
        btnC.setBorderPainted(false);
        btnC.setContentAreaFilled(false);
        btnC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 60, 60));

        btntasbih1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penghitungdzikir/btn1.png"))); // NOI18N
        btntasbih1.setBorder(null);
        btntasbih1.setBorderPainted(false);
        btntasbih1.setContentAreaFilled(false);
        btntasbih1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntasbih1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntasbih1ActionPerformed(evt);
            }
        });
        getContentPane().add(btntasbih1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 100, 100));

        btnbacktasbih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penghitungdzikir/btnBack.png"))); // NOI18N
        btnbacktasbih.setBorder(null);
        btnbacktasbih.setBorderPainted(false);
        btnbacktasbih.setContentAreaFilled(false);
        btnbacktasbih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbacktasbih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacktasbihActionPerformed(evt);
            }
        });
        getContentPane().add(btnbacktasbih, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 80));

        jumlahtasbih.setFont(new java.awt.Font("Futura Bk BT", 0, 48)); // NOI18N
        jumlahtasbih.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jumlahtasbih.setBorder(null);
        jumlahtasbih.setOpaque(false);
        jumlahtasbih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahtasbihActionPerformed(evt);
            }
        });
        getContentPane().add(jumlahtasbih, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 260, 260, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penghitungdzikir/2tasbih.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbacktasbihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacktasbihActionPerformed
        home jump = new home();        
        jump.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbacktasbihActionPerformed

    private void jumlahtasbihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahtasbihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahtasbihActionPerformed

    private int count;
    private void btntasbih1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntasbih1ActionPerformed
        count++;
        jumlahtasbih.setText (Integer.toString(count));
    }//GEN-LAST:event_btntasbih1ActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        int reset = 0;
        jumlahtasbih.setText(String.valueOf(reset));
    }//GEN-LAST:event_btnCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tasbih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tasbih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tasbih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tasbih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tasbih().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnbacktasbih;
    private javax.swing.JButton btntasbih1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jumlahtasbih;
    // End of variables declaration//GEN-END:variables
}
